[build]
  command = "npm run build-netlify"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/dashboard/sense-learn/questions-and-answers/*/send/"
  to = "/dashboard/sense-learn/questions-and-answers/:splat/send/"
  status = 200